# Generated by Django 4.1 on 2022-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="auhtors"),
        ),
    ]
